In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
from datetime import datetime
from googletrans import Translator
import os
import csv


In [2]:


def leer_archivos_csv(ruta_directorio):
    dataframes = {}
    rutas_relativas = os.listdir(ruta_directorio)[:-1]

    for archivo in rutas_relativas:
                año = archivo.split('-')[1][:4] if '-' in archivo else None
                if año:  
                    df = pd.read_csv(os.path.join(ruta_directorio, archivo), delimiter=';')
                    if año not in dataframes:
                        dataframes[año] = []
                        dataframes[año].append(df)

    return dataframes

ruta_directorio = '../datos'
dataframes_por_anio = leer_archivos_csv(ruta_directorio)
dataframe_final = pd.concat([pd.concat(dfs) for dfs in dataframes_por_anio.values()], ignore_index=True)

In [4]:
dataframe_final.shape               #1.026.299 filas y 15 columnas

(1026299, 15)

In [5]:
dataframe_final.duplicated().sum()             #enontramos 274 duplicados en todo el dataframe generado
                                                #Tenemos que tener en cuenta que hemos puesto el AÑO del ejercicio como indice

np.int64(274)

In [6]:
dataframe_final['NOME ÓRGÃO SUPERIOR'].duplicated().sum()       #observamos que el organo superior es 1.026.273 el mismo
dataframe_final['CÓDIGO ÓRGÃO SUPERIOR'].duplicated().sum()     #confirmamos este dato con el codigo del organo superior

np.int64(1026273)

In [7]:
dataframe_final['VALOR PREVISTO ATUALIZADO'].isnull().sum()    # En el valor previsto acutalizado tenemos 51.315 nulos
dataframe_final['VALOR REALIZADO'].isnull().sum()              # En valores realizados 39.465 nulos 

np.int64(39465)

In [8]:
dataframe_final['PERCENTUAL REALIZADO'].isnull().sum()          #Porcentaje realizado 24134 nulos

np.int64(24134)

In [29]:
dataframe_final['NOME ÓRGÃO SUPERIOR'].unique()     #Tenemos los ministerios

array([nan, 'Advocacia-Geral da União', 'Controladoria-Geral da União',
       'Ministério da Agricultura, Pecuária e Abastec',
       'Ministério da Cidadania',
       'Ministério da Ciência, Tecnologia, Inovações ',
       'Ministério da Defesa', 'Ministério da Economia',
       'Ministério da Educação', 'Ministério da Infraestrutura',
       'Ministério da Justiça e Segurança Pública',
       'Ministério da Mulher, Família e Direitos Huma',
       'Ministério da Pesca e Aquicultura',
       'Ministério da Previdência Social', 'Ministério da Saúde',
       'Ministério das Comunicações',
       'Ministério das Mulheres, Igualdade Racial, da',
       'Ministério das Relações Exteriores',
       'Ministério de Minas e Energia',
       'Ministério do Desenvolvimento Agrário',
       'Ministério do Desenvolvimento Regional', 'Ministério do Esporte',
       'Ministério do Meio Ambiente', 'Ministério do Trabalho e Emprego',
       'Ministério do Turismo', 'Presidência da República'], dtype=

In [10]:
dataframe_final['CÓDIGO ÓRGÃO SUPERIOR'].unique()   #codigos de los ministerios

array([63000., 37000.,    nan, 22000., 55000., 24000., 52000., 25000.,
       26000., 39000., 30000., 81000., 58000., 33000., 36000., 41000.,
       57000., 35000., 32000., 49000., 53000., 51000., 44000., 38000.,
       54000., 20000.])

In [11]:
dataframe_final['NOME ÓRGÃO SUPERIOR'].isnull().sum()


np.int64(359206)

In [12]:
dataframe_final.dtypes            #solo tenemos dos datos tipo int los codigos , las damas son object

CÓDIGO ÓRGÃO SUPERIOR        float64
NOME ÓRGÃO SUPERIOR           object
CÓDIGO ÓRGÃO                 float64
NOME ÓRGÃO                    object
CÓDIGO UNIDADE GESTORA       float64
NOME UNIDADE GESTORA          object
CATEGORIA ECONÔMICA           object
ORIGEM RECEITA                object
ESPÉCIE RECEITA               object
DETALHAMENTO                  object
VALOR PREVISTO ATUALIZADO     object
VALOR LANÇADO                 object
VALOR REALIZADO               object
PERCENTUAL REALIZADO          object
DATA LANÇAMENTO               object
dtype: object

In [13]:
dataframe_final.describe(include= 'O').T


count  unique  \
NOME ÓRGÃO SUPERIOR         667093      25   
NOME ÓRGÃO                  991412     287   
NOME UNIDADE GESTORA       1006818     356   
CATEGORIA ECONÔMICA        1007321       5   
ORIGEM RECEITA              987881      15   
ESPÉCIE RECEITA             994372      63   
DETALHAMENTO                996962    1883   
VALOR PREVISTO ATUALIZADO   974984   17702   
VALOR LANÇADO               999880    6633   
VALOR REALIZADO             986834  585595   
PERCENTUAL REALIZADO       1002165     953   
DATA LANÇAMENTO            1002468    2151   

                                                                         top  \
NOME ÓRGÃO SUPERIOR                                   Ministério da Educação   
NOME ÓRGÃO                 Ministério da Economia - Unidades com vínculo ...   
NOME UNIDADE GESTORA                 SETORIAL ORCAMENTARIA E FINANCEIRA / ME   
CATEGORIA ECONÔMICA                                       Receitas Correntes   
ORIGEM RECEITA                                     Outras Receitas Correntes   
ESPÉCIE RECEITA                 Serviços Administrativos e Comerciais Gerais   
DETALHAMENTO                     SERV.ADMINISTRAT.E COMERCIAIS GERAIS-PRINC.   
VALOR PREVISTO ATUALIZADO                                               0,00   
VALOR LANÇADO                                                           0,00   
VALOR REALIZADO                                                         0,00   
PERCENTUAL REALIZADO                                                    0,00   
DATA LANÇAMENTO                                                   31/12/2014   

                             freq  
NOME ÓRGÃO SUPERIOR        235281  
NOME ÓRGÃO                 115437  
NOME UNIDADE GESTORA       106170  
CATEGORIA ECONÔMICA        961527  
ORIGEM RECEITA             310617  
ESPÉCIE RECEITA            269440  
DETALHAMENTO               154458  
VALOR PREVISTO ATUALIZADO  956134  
VALOR LANÇADO              992838  
VALOR REALIZADO             20221  
PERCENTUAL REALIZADO       994924  
DATA LANÇAMENTO              4411

In [14]:
dataframe_final['VALOR LANÇADO'].describe()

count     999880
unique      6633
top         0,00
freq      992838
Name: VALOR LANÇADO, dtype: object

In [15]:
dataframe_final.isnull().sum()
round(dataframe_final.isnull().sum()/dataframe_final.shape[0]*100,2)          #porcentajes en cada columna

CÓDIGO ÓRGÃO SUPERIOR         2.96
NOME ÓRGÃO SUPERIOR          35.00
CÓDIGO ÓRGÃO                  2.45
NOME ÓRGÃO                    3.40
CÓDIGO UNIDADE GESTORA        3.27
NOME UNIDADE GESTORA          1.90
CATEGORIA ECONÔMICA           1.85
ORIGEM RECEITA                3.74
ESPÉCIE RECEITA               3.11
DETALHAMENTO                  2.86
VALOR PREVISTO ATUALIZADO     5.00
VALOR LANÇADO                 2.57
VALOR REALIZADO               3.85
PERCENTUAL REALIZADO          2.35
DATA LANÇAMENTO               2.32
dtype: float64

In [16]:
dataframe_final.to_csv('../Años-Unidos.csv')    #guardamos el nuevo archivo con los csv unidos

In [17]:
dataframe_final['CÓDIGO ÓRGÃO SUPERIOR'].unique()

array([63000., 37000.,    nan, 22000., 55000., 24000., 52000., 25000.,
       26000., 39000., 30000., 81000., 58000., 33000., 36000., 41000.,
       57000., 35000., 32000., 49000., 53000., 51000., 44000., 38000.,
       54000., 20000.])

In [18]:
array = dataframe_final['NOME ÓRGÃO SUPERIOR'].unique()

In [19]:
#Sacamos los codiogos de los ministerios para la sustitucion de datos en los nombres que estaban nulos segun su codigo

resultados = []

for ministerio in array:
    codigo = dataframe_final.loc[dataframe_final['NOME ÓRGÃO SUPERIOR'] == ministerio, 'CÓDIGO ÓRGÃO SUPERIOR']
    resultados.append({'Nome': ministerio, 'Código': codigo.values[0] if not codigo.empty else None})

resultados_df = pd.DataFrame(resultados)
print("\nCódigos correspondientes a los ministerios:")
print(resultados_df)


Códigos correspondientes a los ministerios:
                                             Nome   Código
0                                             NaN      NaN
1                        Advocacia-Geral da União  63000.0
2                    Controladoria-Geral da União  37000.0
3   Ministério da Agricultura, Pecuária e Abastec  22000.0
4                         Ministério da Cidadania  55000.0
5   Ministério da Ciência, Tecnologia, Inovações   24000.0
6                            Ministério da Defesa  52000.0
7                          Ministério da Economia  25000.0
8                          Ministério da Educação  26000.0
9                    Ministério da Infraestrutura  39000.0
10      Ministério da Justiça e Segurança Pública  30000.0
11  Ministério da Mulher, Família e Direitos Huma  81000.0
12              Ministério da Pesca e Aquicultura  58000.0
13               Ministério da Previdência Social  33000.0
14                            Ministério da Saúde  36000.0
15         

In [20]:
dataframe_final['CÓDIGO ÓRGÃO'].unique()            #codigos orgao

array([63000., 66000., 22202., 22000., 22211.,    nan, 44208., 22201.,
       22905., 49001., 55000., 55001., 24000., 20501., 20301., 24901.,
       20502., 24209., 20402., 49280., 52911., 52904., 52132., 52912.,
       52131., 52121., 52111., 31280., 52000., 52133., 52221., 52211.,
       52222., 30203., 25000., 37202., 25205., 20603., 25201., 38901.,
       25208., 33206., 30204., 25203., 37201., 20202., 25915., 25207.,
       25914., 22500., 25901., 25211., 25904., 61201., 28500., 25916.,
       20924., 71902., 25905., 26435., 26276., 26000., 26285., 26233.,
       26407., 26232., 26405., 26292., 26423., 26422., 26251., 26234.,
       26275., 26238., 26261., 26244., 26432., 26414., 26421., 26411.,
       26270., 26417., 26410., 26282., 26430., 26258., 26278., 26416.,
       26253., 26420., 26418., 26408., 26240., 26246., 26433., 26428.,
       26263., 26412., 26404., 26248., 26434., 26409., 26264., 26424.,
       26415., 26291., 26413., 26236., 26243., 26255., 26419., 26247.,
      

In [31]:
dataframe_final['NOME ÓRGÃO'].value_counts()   #nombres orgaos

NOME ÓRGÃO
Ministério da Economia - Unidades com vínculo direto                        115437
Fundo do Exército                                                            24677
Comando da Marinha - Fundo Naval                                             22924
Fundo Nacional de Cultura                                                    15391
Instituto Brasileiro do Meio Ambiente e dos Recursos Naturais Renováveis     13277
                                                                             ...  
Hospital Cristo Redentor S.A.                                                    2
Agência de Desenvolvimento da Amazônia                                           2
Companhia de Desenvolvimento de Barcarena                                        1
Departamento Nacional de Estradas de Rodagem                                     1
Hospital Fêmina S.A.                                                             1
Name: count, Length: 287, dtype: int64

In [34]:
datos = dataframe_final.groupby('CÓDIGO UNIDADE GESTORA')['NOME UNIDADE GESTORA'].first

In [ ]:
dataframe_final['CÓDIGO ÓRGÃO'].reset_index()

In [35]:
datos = dataframe_final.groupby('CÓDIGO ÓRGÃO')['NOME ÓRGÃO'].first()
lista_codig_orgao=list(datos.index)
lista_nombre = list(datos.values)
diccionario_orgao= {}
for i in range(0,len(lista_codig_orgao)):
    diccionario_orgao[lista_codig_orgao[i]]= lista_nombre[i]

diccionario_orgao

{20101.0: 'Presidência da República',
 20116.0: 'Fundo de Imprensa Nacional',
 20117.0: 'Fundo Nacional Antidrogas',
 20122.0: 'Secretaria Nacional de Políticas para Mulheres',
 20129.0: 'Secretaria Especial de Agricultura Familiar e do Desenvolvimento Agrário',
 20202.0: 'Fundação Escola Nacional de Administração Pública',
 20203.0: 'Agência Nacional do Cinema',
 20301.0: 'Comissão Nacional de Energia Nuclear',
 20302.0: 'Nuclebrás Equipamentos Pesados S.A.',
 20303.0: 'Indústrias Nucleares do Brasil',
 20402.0: 'Agência Espacial Brasileira',
 20403.0: 'Fundação Casa de Rui Barbosa',
 20404.0: 'Fundação Biblioteca Nacional',
 20408.0: 'Fundação Cultural Palmares',
 20411.0: 'Instituto do Patrimônio Histórico e Artístico Nacional',
 20412.0: 'Fundação Nacional de Artes',
 20415.0: 'Empresa Brasil de Comunicação',
 20501.0: 'Conselho Nacional de Desenvolvimento Científico e Tecnológico',
 20502.0: 'Financiadora de Estudos e Projetos',
 20603.0: 'Superintendência da Zona Franca de Manaus

In [38]:
dataframe_final.head(2)

CÓDIGO ÓRGÃO SUPERIOR       NOME ÓRGÃO SUPERIOR  CÓDIGO ÓRGÃO  \
ANO EXERCÍCIO                                                                  
NaN                          63000.0                       NaN       63000.0   
2013.0                       63000.0  Advocacia-Geral da União       63000.0   

                                                      NOME ÓRGÃO  \
ANO EXERCÍCIO                                                      
NaN            Advocacia-Geral da União - Unidades com víncul...   
2013.0         Advocacia-Geral da União - Unidades com víncul...   

               CÓDIGO UNIDADE GESTORA  \
ANO EXERCÍCIO                           
NaN                          110060.0   
2013.0                       110060.0   

                                        NOME UNIDADE GESTORA  \
ANO EXERCÍCIO                                                  
NaN            COORD. GERAL DE ORC. FIN. E ANAL. CONT. - AGU   
2013.0         COORD. GERAL DE ORC. FIN. E ANAL. CONT. - AGU   

              CATEGORIA ECONÔMICA             ORIGEM RECEITA  \
ANO EXERCÍCIO                                                  
NaN            Receitas Correntes  Outras Receitas Correntes   
2013.0         Receitas Correntes  Outras Receitas Correntes   

                                             ESPÉCIE RECEITA  \
ANO EXERCÍCIO                                                  
NaN            Bens, Direitos e Valores Incorporados ao Patr   
2013.0           Indenizações, restituições e ressarcimentos   

                                                DETALHAMENTO  \
ANO EXERCÍCIO                                                  
NaN            REC.DIVIDA ATIVA NAO TRIBUTARIA DE OUTRAS REC   
2013.0          RECUPERACAO DE DESPESAS DE EXERC. ANTERIORES   

              VALOR PREVISTO ATUALIZADO VALOR LANÇADO VALOR REALIZADO  \
ANO EXERCÍCIO                                                           
NaN                                0,00          0,00         1297,13   
2013.0                             0,00          0,00     26666621,42   

              PERCENTUAL REALIZADO DATA LANÇAMENTO  
ANO EXERCÍCIO                                       
NaN                           0,00      31/12/2013  
2013.0                        0,00      31/12/2013

In [36]:
datos1 = dataframe_final.groupby('CÓDIGO UNIDADE GESTORA')['NOME UNIDADE GESTORA'].first()
lista_codigo_gesto=list(datos.index)
lista_nombre1 = list(datos1.values)
diccionario_gesto= {}
for i in range(0,len(lista_codigo_gesto)):
    diccionario_gesto[lista_codigo_gesto[i]]= lista_nombre1[i]

diccionario_gesto

{20101.0: 'SECRETARIA DE ADMINISTRACAO-SET.ORC.E FIN./PR',
 20116.0: 'SECRETARIA EXECUTIVA-MPA',
 20117.0: 'COORD. GERAL DE ORC. FIN. E ANAL. CONT. - AGU',
 20122.0: 'GABINETE DA VICE-PRESIDENCIA DA REPUBLICA',
 20129.0: 'DIRETORIA DE GESTAO INTERNA/SE/CGU',
 20202.0: 'FUNDO NACIONAL PARA A CRIANCA E O ADOLESCENTE',
 20203.0: 'FUNDO DE IMPRENSA NACIONAL/EXEC.ORC.FINANC.',
 20301.0: 'FUNDO NACIONAL ANTIDROGAS',
 20302.0: 'SECRETARIA DE ASSUNTOS ESTRATEGICOS-SAE/PR',
 20303.0: 'DEPARTAMENTO DE PLANEJ, ORC E FINANCAS (MD)',
 20402.0: 'SECRETARIA DE AVIACAO CIVIL/PR',
 20403.0: 'FUNDO NACIONAL DE AVIACAO CIVIL',
 20404.0: 'SECRETARIA DE PORTOS/PR',
 20408.0: 'SEC.ESPEC.DE AGRIC.FAMIL.E DO DESENV.AGRARIO',
 20411.0: 'SECRETARIA ESPECIAL DE AQUICULTURA E PESCA/PR',
 20412.0: 'INDUSTRIAS NUCLEARES DO BRASIL S/A - INB',
 20415.0: 'NUCLEBRAS EQUIPAMENTOS PESADOS S/A-NUCLEP',
 20501.0: 'CNEN-ORCAMENTO E FINANCAS',
 20502.0: 'AGENCIA NACIONAL DE AVIACAO CIVIL',
 20603.0: 'SUPERINT. INFRAESTRUTURA