In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
from datetime import datetime
import os
import csv
import sys
sys.path.append("../")
from src import soporte_apertura as sp


In [3]:
ruta_directorio = '../datos'
dataframes_por_anio = sp.leer_archivos_csv(ruta_directorio)
dataframe_final = pd.concat([pd.concat(dfs) for dfs in dataframes_por_anio.values()], ignore_index=True)

In [3]:
dataframe_final.shape               #1.026.299 filas y 15 columnas

(1026299, 16)

In [7]:
dataframe_final.head(2)

CÓDIGO ÓRGÃO SUPERIOR       NOME ÓRGÃO SUPERIOR  CÓDIGO ÓRGÃO  \
0                63000.0                       NaN       63000.0   
1                63000.0  Advocacia-Geral da União       63000.0   

                                          NOME ÓRGÃO  CÓDIGO UNIDADE GESTORA  \
0  Advocacia-Geral da União - Unidades com víncul...                110060.0   
1  Advocacia-Geral da União - Unidades com víncul...                110060.0   

                            NOME UNIDADE GESTORA CATEGORIA ECONÔMICA  \
0  COORD. GERAL DE ORC. FIN. E ANAL. CONT. - AGU  Receitas Correntes   
1  COORD. GERAL DE ORC. FIN. E ANAL. CONT. - AGU  Receitas Correntes   

              ORIGEM RECEITA                                ESPÉCIE RECEITA  \
0  Outras Receitas Correntes  Bens, Direitos e Valores Incorporados ao Patr   
1  Outras Receitas Correntes    Indenizações, restituições e ressarcimentos   

                                    DETALHAMENTO VALOR PREVISTO ATUALIZADO  \
0  REC.DIVIDA ATIVA NAO TRIBUTARIA DE OUTRAS REC                      0,00   
1   RECUPERACAO DE DESPESAS DE EXERC. ANTERIORES                      0,00   

  VALOR LANÇADO VALOR REALIZADO PERCENTUAL REALIZADO DATA LANÇAMENTO  \
0          0,00         1297,13                 0,00      31/12/2013   
1          0,00     26666621,42                 0,00      31/12/2013   

   ANO EXERCÍCIO  
0            NaN  
1         2013.0

In [ ]:
dataframe_final.duplicated().sum()             #enontramos 66 duplicados en todo el dataframe generado
                                            

np.int64(66)

In [5]:
dataframe_final['NOME ÓRGÃO SUPERIOR'].duplicated().sum()       #observamos que el organo superior es 1.026.273 el mismo
dataframe_final['CÓDIGO ÓRGÃO SUPERIOR'].duplicated().sum()     #confirmamos este dato con el codigo del organo superior

np.int64(1026273)

In [11]:
dataframe_final['VALOR PREVISTO ATUALIZADO'].isnull().sum()
print(dataframe_final['VALOR PREVISTO ATUALIZADO'].isnull().sum())        # En el valor previsto acutalizado tenemos 51.315 nulos
dataframe_final['VALOR REALIZADO'].isnull().sum()  
print(dataframe_final['VALOR REALIZADO'].isnull().sum())                  # En valores realizados 39.465 nulos 

51315
39465


In [ ]:
dataframe_final['PERCENTUAL REALIZADO'].isnull().sum()              #Porcentaje realizado =  24134 nulos

np.int64(24134)

In [8]:
dataframe_final['NOME ÓRGÃO SUPERIOR'].unique()     #Tenemos los ministerios

array([nan, 'Advocacia-Geral da União', 'Controladoria-Geral da União',
       'Ministério da Agricultura, Pecuária e Abastec',
       'Ministério da Cidadania',
       'Ministério da Ciência, Tecnologia, Inovações ',
       'Ministério da Defesa', 'Ministério da Economia',
       'Ministério da Educação', 'Ministério da Infraestrutura',
       'Ministério da Justiça e Segurança Pública',
       'Ministério da Mulher, Família e Direitos Huma',
       'Ministério da Pesca e Aquicultura',
       'Ministério da Previdência Social', 'Ministério da Saúde',
       'Ministério das Comunicações',
       'Ministério das Mulheres, Igualdade Racial, da',
       'Ministério das Relações Exteriores',
       'Ministério de Minas e Energia',
       'Ministério do Desenvolvimento Agrário',
       'Ministério do Desenvolvimento Regional', 'Ministério do Esporte',
       'Ministério do Meio Ambiente', 'Ministério do Trabalho e Emprego',
       'Ministério do Turismo', 'Presidência da República'], dtype=

In [9]:
dataframe_final['CÓDIGO ÓRGÃO SUPERIOR'].unique()   #codigos de los ministerios

array([63000., 37000.,    nan, 22000., 55000., 24000., 52000., 25000.,
       26000., 39000., 30000., 81000., 58000., 33000., 36000., 41000.,
       57000., 35000., 32000., 49000., 53000., 51000., 44000., 38000.,
       54000., 20000.])

In [ ]:
dataframe_final['NOME ÓRGÃO SUPERIOR'].isnull().sum()       #Nulos en nombre de organo superior


np.int64(359206)

In [11]:
dataframe_final.dtypes            #solo tenemos dos datos tipo float los codigos y el año del ejercicio , las damas son object, 

CÓDIGO ÓRGÃO SUPERIOR        float64
NOME ÓRGÃO SUPERIOR           object
CÓDIGO ÓRGÃO                 float64
NOME ÓRGÃO                    object
CÓDIGO UNIDADE GESTORA       float64
NOME UNIDADE GESTORA          object
CATEGORIA ECONÔMICA           object
ORIGEM RECEITA                object
ESPÉCIE RECEITA               object
DETALHAMENTO                  object
VALOR PREVISTO ATUALIZADO     object
VALOR LANÇADO                 object
VALOR REALIZADO               object
PERCENTUAL REALIZADO          object
DATA LANÇAMENTO               object
ANO EXERCÍCIO                float64
dtype: object

In [ ]:
dataframe_final['VALOR LANÇADO'].describe()                          

count     999880
unique      6633
top         0,00
freq      992838
Name: VALOR LANÇADO, dtype: object

In [ ]:
dataframe_final.isnull().sum()
round(dataframe_final.isnull().sum()/dataframe_final.shape[0]*100,2).reset_index()        #porcentajes en cada columna de nulos

index      0
0       CÓDIGO ÓRGÃO SUPERIOR   2.96
1         NOME ÓRGÃO SUPERIOR  35.00
2                CÓDIGO ÓRGÃO   2.45
3                  NOME ÓRGÃO   3.40
4      CÓDIGO UNIDADE GESTORA   3.27
5        NOME UNIDADE GESTORA   1.90
6         CATEGORIA ECONÔMICA   1.85
7              ORIGEM RECEITA   3.74
8             ESPÉCIE RECEITA   3.11
9                DETALHAMENTO   2.86
10  VALOR PREVISTO ATUALIZADO   5.00
11              VALOR LANÇADO   2.57
12            VALOR REALIZADO   3.85
13       PERCENTUAL REALIZADO   2.35
14            DATA LANÇAMENTO   2.32
15              ANO EXERCÍCIO  25.00

In [14]:
dataframe_final['CÓDIGO ÓRGÃO SUPERIOR'].unique()


array([63000., 37000.,    nan, 22000., 55000., 24000., 52000., 25000.,
       26000., 39000., 30000., 81000., 58000., 33000., 36000., 41000.,
       57000., 35000., 32000., 49000., 53000., 51000., 44000., 38000.,
       54000., 20000.])

In [13]:
array = dataframe_final['NOME ÓRGÃO SUPERIOR'].unique()

In [ ]:
#Sacamos los codiogos de los ministerios para la sustitucion de datos en los nombres que estaban nulos segun su codigo

resultados = []

for ministerio in array:
    codigo = dataframe_final.loc[dataframe_final['NOME ÓRGÃO SUPERIOR'] == ministerio, 'CÓDIGO ÓRGÃO SUPERIOR']
    resultados.append({'Nome': ministerio, 'Código': codigo.values[0] if not codigo.empty else None})

resultados_df = pd.DataFrame(resultados)
print("\nCódigos correspondientes a los ministerios:")                      #sacamos un diccionario que usaremos posteriormente para nulos
print(resultados_df)


Códigos correspondientes a los ministerios:
                                             Nome   Código
0                                             NaN      NaN
1                        Advocacia-Geral da União  63000.0
2                    Controladoria-Geral da União  37000.0
3   Ministério da Agricultura, Pecuária e Abastec  22000.0
4                         Ministério da Cidadania  55000.0
5   Ministério da Ciência, Tecnologia, Inovações   24000.0
6                            Ministério da Defesa  52000.0
7                          Ministério da Economia  25000.0
8                          Ministério da Educação  26000.0
9                    Ministério da Infraestrutura  39000.0
10      Ministério da Justiça e Segurança Pública  30000.0
11  Ministério da Mulher, Família e Direitos Huma  81000.0
12              Ministério da Pesca e Aquicultura  58000.0
13               Ministério da Previdência Social  33000.0
14                            Ministério da Saúde  36000.0
15         

In [18]:
dataframe_final['CÓDIGO ÓRGÃO'].unique()            #codigos orgao

array([63000., 66000., 22202., 22000., 22211.,    nan, 44208., 22201.,
       22905., 49001., 55000., 55001., 24000., 20501., 20301., 24901.,
       20502., 24209., 20402., 49280., 52911., 52904., 52132., 52912.,
       52131., 52121., 52111., 31280., 52000., 52133., 52221., 52211.,
       52222., 30203., 25000., 37202., 25205., 20603., 25201., 38901.,
       25208., 33206., 30204., 25203., 37201., 20202., 25915., 25207.,
       25914., 22500., 25901., 25211., 25904., 61201., 28500., 25916.,
       20924., 71902., 25905., 26435., 26276., 26000., 26285., 26233.,
       26407., 26232., 26405., 26292., 26423., 26422., 26251., 26234.,
       26275., 26238., 26261., 26244., 26432., 26414., 26421., 26411.,
       26270., 26417., 26410., 26282., 26430., 26258., 26278., 26416.,
       26253., 26420., 26418., 26408., 26240., 26246., 26433., 26428.,
       26263., 26412., 26404., 26248., 26434., 26409., 26264., 26424.,
       26415., 26291., 26413., 26236., 26243., 26255., 26419., 26247.,
      

In [19]:
dataframe_final['NOME ÓRGÃO'].value_counts()   #nombres orgaos

NOME ÓRGÃO
Ministério da Economia - Unidades com vínculo direto                        115437
Fundo do Exército                                                            24677
Comando da Marinha - Fundo Naval                                             22924
Fundo Nacional de Cultura                                                    15391
Instituto Brasileiro do Meio Ambiente e dos Recursos Naturais Renováveis     13277
                                                                             ...  
Hospital Cristo Redentor S.A.                                                    2
Agência de Desenvolvimento da Amazônia                                           2
Companhia de Desenvolvimento de Barcarena                                        1
Departamento Nacional de Estradas de Rodagem                                     1
Hospital Fêmina S.A.                                                             1
Name: count, Length: 287, dtype: int64

In [20]:
datos = dataframe_final.groupby('CÓDIGO UNIDADE GESTORA')['NOME UNIDADE GESTORA'].first

In [21]:
dataframe_final['CÓDIGO ÓRGÃO'].reset_index()

index  CÓDIGO ÓRGÃO
0              0       63000.0
1              1       63000.0
2              2       63000.0
3              3       63000.0
4              4       63000.0
...          ...           ...
1026294  1026294       24208.0
1026295  1026295       24208.0
1026296  1026296       24208.0
1026297  1026297       24208.0
1026298  1026298       24208.0

[1026299 rows x 2 columns]

In [22]:
datos = dataframe_final.groupby('CÓDIGO ÓRGÃO')['NOME ÓRGÃO'].first()
lista_codig_orgao=list(datos.index)
lista_nombre = list(datos.values)
diccionario_orgao= {}
for i in range(0,len(lista_codig_orgao)):
    diccionario_orgao[lista_codig_orgao[i]]= lista_nombre[i]

#diccionario_orgao                                                                  

In [50]:
#dataframe_final.head(2)

In [ ]:
datos1 = dataframe_final.groupby('CÓDIGO UNIDADE GESTORA')['NOME UNIDADE GESTORA'].first()
lista_codigo_gesto=list(datos.index)
lista_nombre1 = list(datos1.values)
diccionario_gesto= {}
for i in range(0,len(lista_codigo_gesto)):
    diccionario_gesto[lista_codigo_gesto[i]]= lista_nombre1[i]

#diccionario_gesto   pero esta vez para los codigos unidades gestoras                                                           

In [16]:
dataframe_final.dtypes.reset_index()                             # vamos a empezar a cambiar tipos da datos

index        0
0       CÓDIGO ÓRGÃO SUPERIOR  float64
1         NOME ÓRGÃO SUPERIOR   object
2                CÓDIGO ÓRGÃO  float64
3                  NOME ÓRGÃO   object
4      CÓDIGO UNIDADE GESTORA  float64
5        NOME UNIDADE GESTORA   object
6         CATEGORIA ECONÔMICA   object
7              ORIGEM RECEITA   object
8             ESPÉCIE RECEITA   object
9                DETALHAMENTO   object
10  VALOR PREVISTO ATUALIZADO   object
11              VALOR LANÇADO   object
12            VALOR REALIZADO   object
13       PERCENTUAL REALIZADO   object
14            DATA LANÇAMENTO   object
15              ANO EXERCÍCIO  float64

In [17]:
dataframe_final.head(2)

CÓDIGO ÓRGÃO SUPERIOR       NOME ÓRGÃO SUPERIOR  CÓDIGO ÓRGÃO  \
0                63000.0                       NaN       63000.0   
1                63000.0  Advocacia-Geral da União       63000.0   

                                          NOME ÓRGÃO  CÓDIGO UNIDADE GESTORA  \
0  Advocacia-Geral da União - Unidades com víncul...                110060.0   
1  Advocacia-Geral da União - Unidades com víncul...                110060.0   

                            NOME UNIDADE GESTORA CATEGORIA ECONÔMICA  \
0  COORD. GERAL DE ORC. FIN. E ANAL. CONT. - AGU  Receitas Correntes   
1  COORD. GERAL DE ORC. FIN. E ANAL. CONT. - AGU  Receitas Correntes   

              ORIGEM RECEITA                                ESPÉCIE RECEITA  \
0  Outras Receitas Correntes  Bens, Direitos e Valores Incorporados ao Patr   
1  Outras Receitas Correntes    Indenizações, restituições e ressarcimentos   

                                    DETALHAMENTO VALOR PREVISTO ATUALIZADO  \
0  REC.DIVIDA ATIVA NAO TRIBUTARIA DE OUTRAS REC                      0,00   
1   RECUPERACAO DE DESPESAS DE EXERC. ANTERIORES                      0,00   

  VALOR LANÇADO VALOR REALIZADO PERCENTUAL REALIZADO DATA LANÇAMENTO  \
0          0,00         1297,13                 0,00      31/12/2013   
1          0,00     26666621,42                 0,00      31/12/2013   

   ANO EXERCÍCIO  
0            NaN  
1         2013.0

In [ ]:
dataframe_final.to_csv('../datos/output/frame.preparacion.csv')                 #guardamos en carpeta output para asi realizar limpieza 
                                                                                #sobre el data frame final.